### ISSUE TITLE
无法正常工作

### ISSUE THREAD

**Issue by UchihaYuki** [sanjusss/aliyun-ddns#45]
开启后日志一直写```成功获取xxx.xxx.top的所有记录，共0条。```然后就没有然后了。
这是我的docker-compose.yml
```yaml
version: '3.8'

services:
    aliyun-ddns:
        image: sanjusss/aliyun-ddns:0.2.7
        container_name: aliyun-ddns
        environment:
          - AKID=xxx
          - AKSCT=xxx
          - DOMAIN=xxx.xxx.top
          - TYPE=AAAA
          - REDO=30
          - TTL=60
```
